#!/usr/bin/env bash
# lib/14-init.sh — `pitcrew init`: look at a project and write a config that
# actually runs it.
#
# This used to emit `echo '>> set PITCREW_BE_CMD for app' && exit 1` for every
# component, so the first thing a newly-initialised project did was fail. It
# now reads the repository (see lib/14-detect.sh) and writes real commands,
# real ports and real health paths.
#
# The config goes into pitcrew's own directory by default, not into the
# project — see lib/15-registry.sh for why. `--in-project` puts it in the
# checkout instead, for a repo whose team all use pitcrew.
#
# Runs BEFORE config resolution (see bin/pitcrew): the whole point is that
# there is no config yet.

# Never silently replace a config.
_init_refuse_existing() { # $1 target, $2 force
  [ -e "$1" ] && [ "$2" != 1 ] && die "$1 already exists — pass --force to replace it"
  return 0
}

_init_rank() { # $1 file name → RANK, lower wins config resolution
  case "$1" in *.yaml) RANK=0 ;; *.yml) RANK=1 ;; *) RANK=2 ;; esac
}

# The registry holds one entry per project, so a re-init in another format
# replaces the old entry instead of leaving a second one that never gets read.
_init_prune_registry() { # $1 slug, $2 the file just written
  local e f
  for e in "${PITCREW_REGISTRY_EXTS[@]}"; do
    f="$PROJECTS_DIR/$1.$e"
    [ "$f" = "$2" ] && continue
    [ -e "$f" ] && { rm -f "$f"; say "    ${C_MUTED}replaced the old ${f##*/} entry${RESET}"; }
  done
  return 0
}

# A config in the checkout is the user's file, so an older one next to it is
# reported, never deleted — but it does stop being read the moment the new one
# lands, and that silence is what has to be broken.
_init_warn_siblings() { # $1 dir, $2 the file just written
  local base=${2##*/} other rank_new rank_old
  _init_rank "$base"; rank_new=$RANK
  for other in "$1/pitcrew.yaml" "$1/pitcrew.yml" "$1/pitcrew.config.sh"; do
    [ "${other##*/}" = "$base" ] && continue
    [ -e "$other" ] || continue
    _init_rank "${other##*/}"; rank_old=$RANK
    if [ "$rank_new" -lt "$rank_old" ]; then
      warn "$other is still there — pitcrew reads $base now, so that file no longer has any effect"
    else
      warn "$other is still there and wins resolution — $base will be ignored until you remove it"
    fi
  done
  return 0
}

_yq() { # $1 → the value as a double-quoted YAML scalar, always safe to emit
  local v=$1
  v=${v//\\/\\\\}
  v=${v//\"/\\\"}
  printf '"%s"' "$v"
}

# The same value, quoted only where leaving it bare would change what it means.
# A generated config is one somebody has to READ, and `name: "fixture"`,
# `max: "2G"`, `port: "8080"` are quotes nobody would have typed.
_yqb() { # $1 → a YAML scalar, bare where that is safe
  local v=$1
  case "$v" in
    '') printf '""'; return ;;
    # Leading or trailing space is significant and a bare scalar loses it.
    ' '*|*' ') _yq "$v"; return ;;
    # A leading indicator character means something else in YAML.
    [-?:,\[\]{}\#\&\*\!\|\>\'\"%@\`]*) _yq "$v"; return ;;
    # ": " makes the tail look like a mapping; " #" makes it look like a
    # comment; a trailing ":" makes the whole thing look like a key.
    *': '*|*' #'*|*:) _yq "$v"; return ;;
  esac
  case "$v" in
    true|True|TRUE|false|False|FALSE|null|Null|NULL|yes|Yes|YES|no|No|NO|on|On|ON|'~')
      _yq "$v"; return ;;
  esac
  printf '%s' "$v"
}

_init_write_yaml() { # $1 dir, $2 name — the detected project, as YAML
  local dir=$1 name=$2 a r
  printf '# %s — generated by `pitcrew init` on %(%Y-%m-%d)T.\n' "${name}" -1
  printf '# A guess, not gospel: check the commands and ports below, then edit freely.\n'
  printf '# Full annotated schema: examples/pitcrew.yaml\n\n'
  printf 'root: %s\n' "$dir"
  printf 'name: %s\n' "$(_yq "$name")"
  printf 'emoji: "🏁"\n\n'
  printf 'apps:\n'
  for a in "${DET_APPS[@]}"; do
    printf '  %s:\n' "$a"
    for r in be fe; do
      [ -n "${DET_DIR[$a.$r]:-}" ] || continue
      detect_split_dir "${P_CMD[$a.$r]}"
      printf '    %s:\n' "$r"
      [ -n "$YDIR" ] && printf '      dir: %s\n' "$(_yq "$YDIR")"
      printf '      cmd: %s\n' "$(_yq "$YCMD")"
      printf '      port: %s\n' "${P_PORT[$a.$r]}"
      [ -n "${P_HEALTH[$a.$r]}" ] && printf '      health: %s\n' "$(_yq "${P_HEALTH[$a.$r]}")"
    done
  done
  printf '\n# ── docker dependencies ────────────────────────────────────────────────────\n'
  if [ ${#DET_DEPS[@]} -gt 0 ]; then
    printf '# Found in this project'"'"'s compose file. These are CONTAINER names — if yours\n'
    printf '# are prefixed by the compose project, correct them, then uncomment.\n'
    printf '# deps: [%s]\n' "$(IFS=,; printf '%s' "${DET_DEPS[*]}")"
    printf '# protected_deps: []      # never stopped by `pitcrew stop --deps`\n'
  else
    printf '# deps: [postgres, redis]\n'
    printf '# protected_deps: [postgres]\n'
  fi
  printf '\n# ── environment prepended to every start command ───────────────────────────\n'
  printf '# env:\n#   be: "JAVA_HOME=$HOME/.sdkman/candidates/java/current"\n#   fe: ""\n'
  printf '\n# ── resource caps and boot timeout ─────────────────────────────────────────\n'
  printf '# max:\n#   be: 8G\n#   fe: 10G\n# wait: 240\n'
}

cmd_init() { # [--in-project] [--force] [--sh] [--name <name>] [<dir>]
  local dir="" name="" in_project=0 force=0 redetect=0 fmt=yaml
  while [ $# -gt 0 ]; do
    case "$1" in
      --in-project) in_project=1; shift ;;
      --detect)     redetect=1; shift ;;
      --force|-f)   force=1; shift ;;
      --sh|--bash)  fmt='sh'; shift ;;
      --yaml)       fmt=yaml; shift ;;
      --name)       [ $# -ge 2 ] || die "--name needs a value"; name=$2; shift 2 ;;
      -*)           die "init: unknown option '$1'" ;;
      *)            dir=$1; shift ;;
    esac
  done
  dir=${dir:-$PWD}
  [ -d "$dir" ] || die "init: no such directory: $dir"
  dir=$(cd "$dir" && pwd)

  # A repo that ships its own config — in either format — has already answered
  # every question this command exists to guess at, and that file wins at
  # resolution time anyway. Point at it rather than keeping a detected copy in
  # the registry that will drift. `--detect` overrides, for a fresh look.
  local existing="" e
  for e in "${PITCREW_CONFIG_NAMES[@]}"; do
    [ -f "$dir/$e" ] && { existing="$dir/$e"; break; }
  done
  if [ -n "$existing" ] && [ "$in_project" != 1 ] && [ "$redetect" != 1 ]; then
    name=${name:-$(basename "$dir")}
    local lslug; lslug=$(project_slug "$name")
    mkdir -p "$PROJECTS_DIR"
    local ltarget
    if config_is_yaml "$existing"; then ltarget="$PROJECTS_DIR/$lslug.yaml"
    else                                ltarget="$PROJECTS_DIR/$lslug.sh"; fi
    _init_refuse_existing "$ltarget" "$force"
    if config_is_yaml "$existing"; then
      {
        printf '# %s — registered by `pitcrew init` on %(%Y-%m-%d)T.\n' "$lslug" -1
        printf '#\n# This project ships its own %s, so this entry just points at it.\n' "${existing##*/}"
        printf '# Edit the config in the repository, not here. `pitcrew init --detect`\n'
        printf '# replaces this with a freshly detected config instead.\n\n'
        # `include:` FIRST, because the loader requires it to be the first key —
        # see lib/18-yaml.sh. `root:` is read textually before the file is
        # loaded at all, so it does not need to lead; writing it first produced
        # a stub that every command then refused to load.
        printf 'include: %s\n' "${existing##*/}"
        printf 'root: %s\n' "$dir"
      } > "$ltarget"
    else
      {
        printf '#!/usr/bin/env bash\n'
        printf '# %s — registered by `pitcrew init` on %(%Y-%m-%d)T.\n' "$lslug" -1
        printf '#\n# This project ships its own pitcrew.config.sh, so this entry just points at\n'
        printf '# it. Edit the config in the repository, not here. `pitcrew init --detect`\n'
        printf '# replaces this with a freshly detected config instead.\n\n'
        printf 'PITCREW_ROOT=%q\n' "$dir"
        printf '# shellcheck source=/dev/null\n'
        printf 'source "$PITCREW_ROOT/pitcrew.config.sh"\n'
      } > "$ltarget"
    fi
    _init_prune_registry "$lslug" "$ltarget"
    project_set_current "$lslug"
    say ""
    ok "registered ${BOLD}$lslug${RESET} ${C_MUTED}→ its own ${existing##*/}${RESET}"
    say "    ${C_MUTED}$existing${RESET}"
    say ""
    return 0
  fi

  say ""
  say "  ${C_MUTED}looking at${RESET} ${BOLD}$dir${RESET}"

  detect_plan "$dir"

  if [ ${#DET_APPS[@]} -eq 0 ]; then
    warn "nothing recognisable found in $dir"
    say "  ${C_MUTED}pitcrew looks for gradle, maven, npm, go, cargo, django, python and ruby${RESET}"
    say "  ${C_MUTED}projects, either at the top level or under apis/ apps/ packages/ services/${RESET}"
    say "  ${C_MUTED}Write the config by hand instead: see examples/pitcrew.config.example.sh${RESET}"
    return 1
  fi

  name=${name:-$(basename "$dir")}
  local slug; slug=$(project_slug "$name")

  local target d
  if [ "$in_project" = 1 ]; then
    [ "$fmt" = yaml ] && target="$dir/pitcrew.yaml" || target="$dir/pitcrew.config.sh"
  else
    mkdir -p "$PROJECTS_DIR"
    [ "$fmt" = yaml ] && target="$PROJECTS_DIR/$slug.yaml" || target="$PROJECTS_DIR/$slug.sh"
  fi
  _init_refuse_existing "$target" "$force"

  # ── write it ──
  if [ "$fmt" = yaml ]; then
    _init_write_yaml "$dir" "$name" > "$target"
  else
  {
    printf '#!/usr/bin/env bash\n'
    printf '# %s — generated by `pitcrew init` on %(%Y-%m-%d)T.\n' "${target##*/}" -1
    printf '# A guess, not gospel: check the commands and ports below, then edit freely.\n'
    printf '# Full annotated schema: examples/pitcrew.config.example.sh\n\n'
    printf 'PITCREW_ROOT=%q\n' "$dir"
    printf 'PITCREW_PROJECT_NAME=%q\n' "$name"
    printf 'PITCREW_EMOJI="🏁"\n\n'
    printf 'PITCREW_APPS=(%s)\n\n' "${DET_APPS[*]}"

    local a r line
    for a in "${DET_APPS[@]}"; do
      printf '# %s' "$a"
      for r in be fe; do
        [ -n "${DET_DIR[$a.$r]:-}" ] && printf '  ·  %s: %s (%s)' "$r" "${DET_DIR[$a.$r]#"$dir"/}" "${P_KIND[$a.$r]}"
      done
      printf '\n'
      printf 'pitcrew_app %s' "$a"
      for r in be fe; do
        d=${DET_DIR[$a.$r]:-}; [ -n "$d" ] || continue
        printf ' \\\n  --%s-cmd "%s" --%s-port %s' "$r" "${P_CMD[$a.$r]}" "$r" "${P_PORT[$a.$r]}"
        [ -n "${P_HEALTH[$a.$r]}" ] && printf ' \\\n  --%s-health "%s"' "$r" "${P_HEALTH[$a.$r]}"
        if [ -d "$d/src" ]; then printf ' \\\n  --watch-%s "$ROOT/%s/src"' "$r" "${d#"$dir"/}"
        else                     printf ' \\\n  --watch-%s "$ROOT/%s"'     "$r" "${d#"$dir"/}"; fi
      done
      printf '\n\n'
    done

    printf '# ── docker dependencies ─────────────────────────────────────────────────────\n'
    if [ ${#DET_DEPS[@]} -gt 0 ]; then
      printf '# Found in this project'"'"'s compose file. These are CONTAINER names — if yours\n'
      printf '# are prefixed by the compose project, correct them, then uncomment.\n'
      printf '# PITCREW_DEPS=(%s)\n' "${DET_DEPS[*]}"
      printf '# PITCREW_PROTECTED_DEPS=()   # never stopped by `pitcrew stop --deps`\n'
    else
      printf '# PITCREW_DEPS=(postgres redis)\n'
      printf '# PITCREW_PROTECTED_DEPS=(postgres)\n'
    fi
    printf '\n'
    printf '# ── environment prepended to every start command ────────────────────────────\n'
    printf '# PITCREW_BE_ENV="JAVA_HOME=$HOME/.sdkman/candidates/java/current"\n'
    printf '# PITCREW_FE_ENV=""\n\n'
    printf '# ── resource caps and boot timeout ──────────────────────────────────────────\n'
    printf '# PITCREW_BE_MAX="8G"\n# PITCREW_FE_MAX="10G"\n# PITCREW_WAIT_SECS=240\n'
  } > "$target"
  fi

  if [ "$in_project" = 1 ]; then _init_warn_siblings "$dir" "$target"
  else                           _init_prune_registry "$slug" "$target"; fi

  # ── report ──
  say ""
  local a r n_be=0 n_fe=0 guessed=0
  for a in "${DET_APPS[@]}"; do
    printf '    %b%-18s%b' "$C_ACCENT" "$a" "$RESET"
    for r in be fe; do
      [ -n "${DET_DIR[$a.$r]:-}" ] || continue
      [ "$r" = be ] && n_be=$((n_be + 1)) || n_fe=$((n_fe + 1))
      printf ' %b%s%b %b:%s%b %b%s%b' "$C_SUBTLE" "$r" "$RESET" \
        "$C_MUTED" "${P_PORT[$a.$r]}" "$RESET" "$C_FAINT" "${P_KIND[$a.$r]}" "$RESET"
    done
    printf '\n'
  done
  say ""
  ok "wrote ${BOLD}$target${RESET}"
  say "    ${C_MUTED}${#DET_APPS[@]} apps · $n_be backend · $n_fe frontend${RESET}"

  if [ "$in_project" != 1 ]; then
    project_set_current "$slug"
    say "    ${C_MUTED}registered as${RESET} ${BOLD}$slug${RESET} ${C_MUTED}and made current${RESET}"
  fi
  say ""
  say "  ${C_MUTED}next:${RESET} ${BOLD}pitcrew doctor${RESET} ${C_MUTED}to sanity-check it, then${RESET} ${BOLD}pitcrew${RESET}"
  say "  ${C_MUTED}ports and commands are inferred — ${RESET}${BOLD}pitcrew edit${RESET}${C_MUTED} to correct them${RESET}"
  say ""
  return 0
}
