#!/usr/bin/env bash
# lib/14-init.sh — `pitcrew init`: generate a starter pitcrew.config.sh so a
# new project doesn't start from "no pitcrew.config.sh found" + a manual copy
# of examples/pitcrew.config.example.sh. Runs BEFORE config resolution (see
# bin/pitcrew) since the whole point is that no config exists yet.

cmd_init() { # $1 = target dir, default $PWD
  local dir=${1:-$PWD}
  [ -d "$dir" ] || die "init: no such directory: $dir"
  dir=$(cd "$dir" && pwd)
  local target="$dir/pitcrew.config.sh"
  [ -e "$target" ] && die "init: $target already exists — remove it first if you want to regenerate"

  local name="" emoji="" apps_raw=""
  if [ -t 0 ]; then
    read -r -p "Project name [$(basename "$dir")]: " name
    read -r -p "Emoji [🏁]: " emoji
    read -r -p "App names, space-separated (e.g. \"api web\") [app]: " apps_raw
  fi
  name="${name:-$(basename "$dir")}"
  emoji="${emoji:-🏁}"
  apps_raw="${apps_raw:-app}"

  # sanitize each app token down to what's safe as an associative-array key
  # and a systemd scope/log-file name component
  local apps=() a clean
  for a in $apps_raw; do
    clean=$(printf '%s' "$a" | tr -c 'A-Za-z0-9_-' '-')
    [ -n "$clean" ] && apps+=("$clean")
  done
  [ ${#apps[@]} -gt 0 ] || die "init: no valid app names in '$apps_raw'"

  {
    printf '#!/usr/bin/env bash\n'
    printf '# pitcrew.config.sh — generated by `pitcrew init`. Edit freely.\n'
    printf '# Full annotated schema: examples/pitcrew.config.example.sh in the pitcrew repo.\n'
    printf '# One-call-per-app shorthand: pitcrew_app <name> --be-cmd ... --be-port ... \\\n'
    printf '#   [--fe-cmd ...] [--fe-port ...] [--url-path ...] [--be-health ...] [--watch-be ...] [--watch-fe ...]\n'
    printf '# (or skip it and set PITCREW_BE_CMD[app]=... etc directly — see the example file)\n\n'
    printf 'PITCREW_PROJECT_NAME=%q\n' "$name"
    printf 'PITCREW_EMOJI=%q\n\n' "$emoji"
    printf 'PITCREW_APPS=(%s)\n\n' "${apps[*]}"

    local i=0 app port_be port_fe
    for app in "${apps[@]}"; do
      port_be=$((9000 + i * 2))
      port_fe=$((9001 + i * 2))
      cat <<EOF
pitcrew_app $app \\
  --be-cmd "echo '>> set PITCREW_BE_CMD for $app in pitcrew.config.sh' && exit 1" --be-port $port_be \\
  --fe-cmd "echo '>> set PITCREW_FE_CMD for $app in pitcrew.config.sh' && exit 1" --fe-port $port_fe
  # drop --fe-cmd/--fe-port above if $app has no frontend (or --be-* if backend-only)

EOF
      i=$((i + 1))
    done

    cat <<'EOF'
# ── docker deps (optional) ──────────────────────────────────────────────────
# PITCREW_DEPS=(postgres redis)
# PITCREW_PROTECTED_DEPS=(postgres)   # never auto-stopped by `pitcrew stop --deps`

# ── env for every backend/frontend start command (optional) ────────────────
# PITCREW_BE_ENV="RAILS_ENV=development"
# PITCREW_FE_ENV=""

# ── quick shells (optional) ─────────────────────────────────────────────────
# declare -A PITCREW_SHELLS=([db]="docker exec -it postgres psql -U postgres")
EOF
  } > "$target"

  ok "wrote $target"
  say "  fill in the ${BOLD}--be-cmd${RESET}/${BOLD}--fe-cmd${RESET} placeholders, then: ${BOLD}pitcrew doctor${RESET}"
}
